name: haiko-xmd-3
services:
  - name: kyrox-2._m-d
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin


      
